---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-type-api
  annotations:
    app: nodeport-type-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeport-type-api
  template:
    metadata:
      labels:
        app: nodeport-type-api
    spec:
      containers:
        - name: nodeport-type-api
          image: gcr.io/<project-id>/python-ping-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-type-api
  annotations:
    app: nodeport-type-api
spec:
  selector:
    app: nodeport-type-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 32000
      protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodeport-type-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeport-type-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50